name: .NET

on:
  push:
    branches: 
      - master
      - dev
      - "dev/**"
  pull_request:
    branches:
      - master
      - dev
      - "dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  lint-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Package
        working-directory: ./ClientApp
        run: npm install
      - name: Lint test
        working-directory: ./ClientApp
        run: npm run lint -- --fix
